# Generated by Django 3.1.12 on 2022-11-27 11:54

import SmartDjango.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskuser',
            name='path',
            field=SmartDjango.models.fields.CharField(default=None, max_length=20),
        ),
    ]
