# Generated by Django 3.1.12 on 2022-11-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0002_diskuser_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskuser',
            name='path',
        ),
    ]
