# Generated by Django 3.1.12 on 2022-11-28 13:06

import SmartDjango.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0003_remove_diskuser_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskuser',
            name='alert_percentage',
            field=SmartDjango.models.fields.IntegerField(default=10),
        ),
    ]
