# Generated by Django 3.1.12 on 2022-11-28 03:35

import SmartDjango.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bark_status',
            field=SmartDjango.models.fields.IntegerField(choices=[(0, 'WAIT_BIND'), (1, 'WAIT_CAPTCHA'), (2, 'ACTIVATED')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_status',
            field=SmartDjango.models.fields.IntegerField(choices=[(0, 'WAIT_BIND'), (1, 'WAIT_CAPTCHA'), (2, 'ACTIVATED')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_status',
            field=SmartDjango.models.fields.IntegerField(choices=[(0, 'WAIT_BIND'), (1, 'WAIT_CAPTCHA'), (2, 'ACTIVATED')], default=0),
        ),
    ]
